package com.xdev.rcdemo.mobilekit.ui;

import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.Button;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.xdev.mobile.service.camera.CameraOptions;
import com.xdev.mobile.service.camera.CameraService;
import com.xdev.mobile.service.camera.ImageData;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevImage;
import com.xdev.ui.XdevView;

public class CameraView extends XdevView {

	/**
	 *
	 */
	public CameraView() {
		super();
		this.initUI();
	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);

	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdOpenCamera}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdOpenCamera_buttonClick(final Button.ClickEvent event) {

		CameraService.getInstance().getPicture(CameraOptions.takeAndReturnPicture(),data->{
			showPicture(data);
		}, error->{
			Notification.show(error.getMessage(), Type.ERROR_MESSAGE);
		});
	}

	private void showPicture(final ImageData data){

		this.image.setSource(data.toResource());
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.navBar = new NavBar();
		this.cmdOpenCamera = new XdevButton();
		this.image = new XdevImage();

		this.navBar.setTitle("Camera");
		this.cmdOpenCamera.setCaption("Take Picture");

		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(3);
		this.navBar.setWidth(100, Unit.PERCENTAGE);
		this.navBar.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.navBar, 0, 0);
		this.cmdOpenCamera.setWidth(100, Unit.PERCENTAGE);
		this.cmdOpenCamera.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.cmdOpenCamera, 0, 1);
		this.image.setSizeFull();
		this.gridLayout.addComponent(this.image, 0, 2);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(2, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();

		this.cmdOpenCamera.addClickListener(event -> this.cmdOpenCamera_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton cmdOpenCamera;
	private XdevImage image;
	private NavBar navBar;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
