
package com.xdev.rcdemo.mobilekit.ui;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.ui.Transport;
import com.xdev.ui.XdevUI;
import com.xdev.ui.navigation.XdevNavigator;

@Push(value = PushMode.MANUAL, transport = Transport.LONG_POLLING)
@Theme("rapidclipse_demo_mobilekit")
public class MainUI extends XdevUI {
	public MainUI() {
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void init(final VaadinRequest request) {
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.navigator = new XdevNavigator(this, this);
	
		this.navigator.addView("", MainView.class);
		this.navigator.addView("accelerometer", AccelerometerView.class);
		this.navigator.addView("app", AppView.class);
		this.navigator.addView("barcodescanner", BarcodescannerView.class);
		this.navigator.addView("camera", CameraView.class);
		this.navigator.addView("compass", CompassView.class);
		this.navigator.addView("contacts", ContactsView.class);
		this.navigator.addView("deviceinfo", DeviceInfoView.class);
		this.navigator.addView("geolocation", GeolocationView.class);
		this.navigator.addView("nfc", NfcView.class);
		this.navigator.addView("sms", SmsView.class);
		this.navigator.addView("vibration", VibrationView.class);
	
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevNavigator navigator; // </generated-code>
}